spring.application.name=LMS


spring.datasource.platform=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/lms_database?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=Europe/Belgrade
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=zoranavukadinovic



spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# If you have data.sql/schema.sql and want them to run, keep this ON (newer Boot):
spring.sql.init.mode=never

#spring.datasource.initialization-mode=always


spring.jackson.serialization.fail-on-empty-beans=false


jwt.secret=JhU2&vL9@hQ#8!DxlZGhRtX#G@lEkV^jUoF0Hp$QlY3rQWm!
jwt.expiration=86400000
